location_choices = {
  '1':'Mwiyogo/EndaraSha',
  '2':'Gatarakwa',
  '3':'Thegu River',
  '4':'Kabaru',
  '5':'Gakawa',
  '6':'Mathira	Ruguru',
  '7':'Magutu',
  '8':'Iriani',
  }

sublocation_choices = {
  '1':'Tetu',
  '2':'Kieni',
  '3':'Mathira',
  '4':'Othaya',
  '5':'Mukurweini',
  '6':'Nyeri Town',
  '7':'Ndia',
  '8':'Muks',
}

subcounty_choices = {
        'Ba': 'Baragoi',
        'AL': 'Bungoma',
        'AR': 'Busia',
        'AS': 'Butere',
        'AZ': 'Dadaab',
        'CA': 'Diani Beach',
        'CO': 'Eldoret',
        'CT': 'Emali',
        'DC': 'Embu',
        'DE': 'Garissa',
        'FL': 'Hola',
        'GA': 'Homa Bay',
        'GU': 'Guam',
        'HI': 'Isiolo',
        'IA': 'Kitui',
        'ID': 'Kibwezi',
        'IL': 'Kajiado',
        'IN': 'Kakuma',
        'KS': 'Kapenguria',
        'KY': 'Keroka',
        'LA': 'Kiambu',
        'MA': 'Kilifi',
        'MD': 'Kisii',
        'ME': 'Kisumu',
        'MI': 'Kitale',
        'MN': 'Mandera',
        'MO': 'Malindi',
        'MP': 'Makindu',
        'MS': 'Machakos',
        'MT': 'Loyangalani',
        'NA': 'Londiani',
        'NC': 'Lokichoggio',
        'WY': 'Lodwar'
}
